### ISSUE TITLE
No support for HTTP HEAD requests

### ISSUE THREAD

**Issue by ethauvin** [rife2/rife2#55] opened 2024-12-04 13:30 UTC
HTTP HEAD requests always returns a 404 on valid routes:

```console
> curl http://localhost:8080/up
<!DOCTYPE html>
<html lang=en>
<head>
    <title>Server Status</title>
    <meta charset=utf-8>
    <meta name=viewport content="width=device-width, initial-scale=1.0">
</head>
<body>
    
    <h2>Server is UP!</h2>
    <small>2 minutes</small>
    
</body>
</html>
```

```console
> curl --head http://localhost:8080/up
HTTP/1.1 404 Not Found
Server: Jetty(12.0.15)
Date: Wed, 04 Dec 2024 13:19:57 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
```

**Comment by gbevin** [comment] 2024-12-05 07:57
Did you create a route to handle it?

**Comment by ethauvin** [comment] 2024-12-05 13:09
Yes, as shown in the first curl request.

**Comment by gbevin** [comment] 2024-12-05 15:03
@ethauvin any specific method like `get()` and `post()` only handle those methods, by design. If you don't want to have a specific method, you need to use `route()` and you can check for the method in the element implementation, or just accept anything.

**Comment by ethauvin** [comment] 2024-12-05 15:12
Okay. This should be documented somewhere, as it is a non-standard approach to handling `GET` and `POST` requests.

**Comment by gbevin** [comment] 2024-12-05 15:23
Just read up on this. It seems tricky to handle automatically, because anything can be executed in the element that would be handling the get requests. It seems dangerous to implicitly execute it and only pass on the headers while discarding the body. Thoughts?

**Comment by ethauvin** [comment] 2024-12-05 15:32
Isn't that exact definition of a `HEAD` request? A `GET` without a body?

The other issue I'm seeing is that there is no `route()` that allows you to specify the methods. Looks like an oversight. I think I would be fine with documenting the `GET`/`POST` behavior, and adding the missing `route()`. I can submit a PR.

**Comment by gbevin** [comment] 2024-12-05 15:34
I'm concerned at the unintended side effect of implicitly executing an entire element that services a GET request only to provide the headers.

**Comment by gbevin** [comment] 2024-12-05 15:35
Yes, I notice that missing route method too, that would be definitely good to add

**Comment by ethauvin** [comment] 2024-12-05 15:36
I don't get that.  That's what HEAD does in any container I've seen.

**Comment by gbevin** [comment] 2024-12-05 15:39
I've never used containers, so I wouldn't know. Probably it's just my overlay concerned instinct talking. If I would make that automatic in RIFE2, I would like to evaluate first if other web frameworks with per-method routing also do this.

**Comment by ethauvin** [comment] 2024-12-05 15:41
Just look at servlets, `HEAD` is handled with `GET` and `POST`.

**Comment by ethauvin** [comment] 2024-12-05 15:42
Spring is the same way, it's done transparently.

**Comment by ethauvin** [comment] 2024-12-05 18:48
This is what I did using #56:

```java
 private Route getHead(String path, Class<? extends Element> element) {
    return route(path, new RequestMethod[]{RequestMethod.GET, RequestMethod.HEAD}, element);
 }
```

**Comment by ethauvin** [comment] 2024-12-13 08:53
@gbevin I think we should implement `getHead()`, `postHead()` and `getPostHead()` for now, and document it.

It doesn't break anything, and give us the transparency that other frameworks already have. Let me know if you want to me to amend the PR, I already have the code working on my blog.

**Comment by gbevin** [comment] 2024-12-13 14:00
I hope to be able to have some cycles to think about this during the weekend, though `getHead` ... not the most fortunate name :-D

**Comment by ethauvin** [comment] 2024-12-13 14:05
Not sure I get what you mean. What about things getPost?

**Comment by ethauvin** [comment] 2024-12-13 14:08
> I hope to be able to have some cycles to think about this during the weekend, though `getHead` ... not the most fortunate name :-D 

Some would disagree. 😂

**Comment by gbevin** [comment] 2024-12-17 03:18
Yeah, let's add those methods, and `head()` probably also.

**Comment by gbevin** [comment] 2024-12-17 13:49
Though I would name them `headGet` and `headPost` since the head operation is lighter and it would make it easier to scan through the routes that support head methods

**Comment by ethauvin** [comment] 2024-12-17 13:54
Just in time. I was about to submit the PR.

**Comment by gbevin** [comment] 2024-12-18 02:56
Reviewed and merged, thank you!

**Closed by gbevin** 2024-12-18 02:56 UTC
Labels: bug
